name: jwst-masterclass
channels:
- http://ssb.stsci.edu/astroconda
- defaults
dependencies:
# Python,  jwst_gtvt python<=3.7
- python<=3.7
# Environment support packages
- ipykernel
# Masterclass packages
- cfitsio
- ds9
- pyds9
- fftw
- pyfftw
- fitsverify

- _libgcc_mutex
- ca-certificates
- ld_impl_linux-64
- libstdcxx-ng
- libgcc-ng
- libffi
- ncurses
- openssl
- xz
- zlib
- libedit
- readline
- tk
- sqlite
- certifi
- setuptools
- wheel
- pip

- pip:
# Environment support packages
  - asdf==2.5.2
  - astropy==4.0.1.post1
  - astroquery==0.4.1.dev6145
  - astroscrappy==1.0.8
  - crds[aws]==7.4.1.3
  - cubeviz==0.3.0
  - docutils<0.16
  - dust_extinction==0.9
  - gwcs==0.13.0
  - fitsblender==0.3.6
  - ginga
  - glue-core
  - glue-vispy-viewers
  - jplephem==2.14
  - jwst-footprints==2.4.2
  - jwxml==0.3.0
  - git+https://github.com/spacetelescope/jwst-visit-parser.git@0.1.3
  - git+https://github.com/spacetelescope/jwst_gtvt.git
  - jwxml==0.3.0
  - matplotlib
  - numpy
  - pandas
  - git+https://github.com/spacetelescope/pandokia.git@2.4.1
  - photutils
  - poppy==0.9.0
  - pysiaf==0.9.0
  - pysynphot==0.9.14
  - python-daemon
  - scikit-image
  - scikit-learn
  - scipy
  - stsci.tools==3.6.0
  - stsci.image==2.3.3
  - stsci.imagestats==1.6.2
  - stsci.stimage==0.2.4
  - stsci-rtd-theme
  - sphinx-rtd-theme
  - synphot==0.3
  - webbpsf==0.9.0
# Masterclass packages
  - git+https://github.com/spacetelescope/jwst.git@0.16.1
  - jwst-backgrounds==1.1.2
  - pandeia-engine==1.5.1
  - git+https://github.com/spacetelescope/pandeia-coronagraphy.git@1d5ad4c
  - git+https://github.com/vortex-exoplanet/VIP.git@104bda7
