name: mirage
channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
# Python
- python==3.7.7
# Environment support packages
- ipykernel
# Mirage dependencies
- h5py
- pip
- yaml
- pip:
  # Mirage dependencies
  - astroquery==0.4.1.dev6145
  - asdf==2.5.2
  - astropy==4.0.1.post1
  - gwcs==0.13.0
  - healpy==1.13.0
  - crds[aws]
  - jwst-backgrounds==1.1.2
  - jwxml==0.3.0
  - matplotlib
  - numpy>=1.17.3
  - photutils>=0.7.1
  - poppy==0.9.0
  - pysiaf==0.9.0
  - pysynphot==0.9.14
  - pytest
  - scipy
  - sphinx
  - webbpsf==0.9.0
  - git+https://github.com/npirzkal/NIRCAM_Gsim.git@b420a0a
  - git+https://github.com/npirzkal/GRISMCONF.git@c5509a2
  - git+https://github.com/spacetelescope/jwst.git@0.16.1
  - git+https://github.com/spacetelescope/mirage.git@25df1e3
